export const commonSx = {
  navBarAppBar: (theme) => ({
    bgcolor: theme.palette.background.paper,
    color: theme.palette.text.primary,
    borderBottom: `1px solid ${theme.palette.divider}`,
  }),
  navBarToolbar: {
    minHeight: 64,
    display: "grid",
    gridTemplateColumns: { xs: "auto minmax(0, 1fr) auto", md: "auto minmax(0, 720px) auto" },
    alignItems: "center",
    columnGap: { xs: 1, md: 2 },
  },
  navBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    minWidth: 0,
  },
  navBarSearchWrap: {
    width: "100%",
    minWidth: 0,
    justifySelf: "center",
  },
  navBarRight: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: { xs: 0.5, sm: 1.5 },
    flexShrink: 0,
    minWidth: 0,
  },
  navBarUploadButton: {
    minWidth: { xs: 36, sm: 44 },
    px: { xs: 0.8, sm: 2 },
    whiteSpace: "nowrap",
    "& .MuiButton-startIcon": { mr: { xs: 0, sm: 1 } },
  },
  navBarLoginButton: {
    minWidth: { xs: 36, sm: 44 },
    px: { xs: 0.8, sm: 2 },
    whiteSpace: "nowrap",
    "& .MuiButton-startIcon": { mr: { xs: 0, sm: 1 } },
  },
  searchField: {
    width: "100%",
    maxWidth: 500,
    minWidth: 0,
    "& .MuiInputBase-root": {
      borderRadius: "40px",
      height: { xs: 40, sm: 45 },
      backgroundColor: "background.paper",
    },
  },
  searchIcon: (theme) => ({ color: theme.palette.text.secondary }),
  sideBarDrawer: {
    "& .MuiDrawer-paper": (theme) => ({
      width: { xs: "85vw", sm: 260 },
      maxWidth: 320,
      top: 64,
      height: "calc(100% - 64px)",
      bgcolor: theme.palette.background.paper,
      borderRight: `1px solid ${theme.palette.divider}`,
      backgroundImage: "none",
    }),
  },
  sideBarRoot: { display: "flex", flexDirection: "column", height: "100%" },
  sideBarList: (theme) => ({
    flexGrow: 1,
    overflowY: "auto",
    color: theme.palette.text.primary,
    "& .MuiListItemText-primary": { color: theme.palette.text.primary },
    "& .MuiListItemText-secondary": { color: theme.palette.text.secondary },
    "& .MuiListItemButton-root:hover": { backgroundColor: theme.palette.action.hover },
  }),
  sideBarPrimaryIcon: (theme) => ({ mr: 1, color: theme.palette.text.primary }),
  sideBarIcon: (theme) => ({ mr: 1, color: theme.palette.text.primary }),
  sideBarChannelText: { ml: 1 },
  sideBarChannelPrimary: (theme) => ({ color: theme.palette.text.primary, fontSize: 14 }),
  sideBarTogglePrimary: (theme) => ({ color: theme.palette.text.secondary, fontSize: 13 }),
  sideBarDivider: (theme) => ({ my: 1, borderColor: theme.palette.divider }),
  userAvatar: (size) => ({
    width: size,
    height: size,
    fontSize: Math.round(size * 0.42),
    lineHeight: 1,
    color: "common.white",
    bgcolor: "grey.500",
  }),
};
