export const commonSx = {
  navBarAppBar: (theme) => ({
    bgcolor: theme.palette.mode === "light" ? "rgba(255,255,255,0.92)" : "rgba(24,24,24,0.92)",
    color: theme.palette.text.primary,
    borderBottom: `1px solid ${theme.palette.divider}`,
    backdropFilter: "blur(10px)",
    boxShadow: theme.palette.mode === "light" ? "0 4px 16px rgba(15,23,42,0.06)" : "0 4px 16px rgba(0,0,0,0.35)",
  }),
  navBarToolbar: {
    minHeight: { xs: 56, sm: 64 },
    display: "grid",
    gridTemplateColumns: {
      xs: "auto minmax(0, 1fr) auto",
      md: "minmax(0, 1fr) minmax(360px, 760px) minmax(0, 1fr)",
      xl: "minmax(0, 1fr) minmax(420px, 860px) minmax(0, 1fr)",
    },
    alignItems: "center",
    columnGap: { xs: 0.5, sm: 1, md: 2 },
  },
  navBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: { xs: 0.25, sm: 1 },
    minWidth: 0,
    justifySelf: "start",
    ml: { xs: 0.25, sm: 0.5, md: 1.5 },
  },
  navBarSearchWrap: {
    width: "100%",
    minWidth: 0,
    justifySelf: "center",
  },
  navBarRight: {
    display: "flex",
    alignItems: "center",
    gap: { xs: 0.75, sm: 1.25, md: 1.5 },
    flexShrink: 0,
    minWidth: 0,
    justifySelf: "end",
  },
  navBarUploadButton: {
    minWidth: { xs: 34, sm: 42 },
    height: { xs: 34, sm: 38 },
    px: { xs: 0.6, sm: 1.5 },
    whiteSpace: "nowrap",
    fontWeight: 600,
    "& .MuiButton-startIcon": { mr: { xs: 0, sm: 1 } },
  },
  navBarLoginButton: {
    minWidth: { xs: 34, sm: 42 },
    height: { xs: 34, sm: 38 },
    px: { xs: 0.6, sm: 1.5 },
    whiteSpace: "nowrap",
    fontWeight: 600,
    "& .MuiButton-startIcon": { mr: { xs: 0, sm: 1 } },
  },
  searchField: {
    width: "100%",
    maxWidth: { xs: "100%", sm: 520 },
    minWidth: 0,
    "& .MuiInputBase-root": {
      borderRadius: "40px",
      height: { xs: 36, sm: 42 },
      backgroundColor: "background.paper",
      border: "1px solid",
      borderColor: "divider",
      transition: "border-color 0.2s ease, box-shadow 0.2s ease, background-color 0.2s ease",
      "&:hover": {
        borderColor: "text.secondary",
      },
      "&.Mui-focused": {
        borderColor: "text.primary",
        boxShadow: (theme) => theme.palette.mode === "light"
          ? "0 0 0 3px rgba(17,17,17,0.08)"
          : "0 0 0 3px rgba(255,255,255,0.12)",
      },
    },
  },
  searchIcon: (theme) => ({ color: theme.palette.text.secondary }),
  sideBarDrawer: {
    "& .MuiDrawer-paper": (theme) => ({
      width: { xs: "84vw", sm: 248 },
      maxWidth: 280,
      top: { xs: 56, sm: 64 },
      height: { xs: "calc(100% - 56px)", sm: "calc(100% - 64px)" },
      bgcolor: theme.palette.background.paper,
      borderRight: `1px solid ${theme.palette.divider}`,
      backgroundImage: "none",
      boxShadow: theme.palette.mode === "light" ? "0 10px 28px rgba(15,23,42,0.12)" : "0 10px 30px rgba(0,0,0,0.45)",
    }),
  },
  sideBarRoot: { display: "flex", flexDirection: "column", height: "100%", py: 0.75 },
  sideBarList: (theme) => ({
    flexGrow: 1,
    overflowY: "auto",
    color: theme.palette.text.primary,
    px: 0.25,
    "& .MuiListItem-root": {
      px: 0,
      py: 0,
    },
    "& .MuiListItemText-primary": { color: theme.palette.text.primary },
    "& .MuiListItemText-secondary": { color: theme.palette.text.secondary },
    "& .MuiListItemButton-root": {
      borderRadius: 2.5,
      marginLeft: 0.5,
      marginRight: 0.5,
      minHeight: 40,
      paddingLeft: 1.25,
      paddingRight: 1.25,
      transition: "background-color 180ms ease, color 180ms ease",
    },
    "& .MuiListItemButton-root:hover": { backgroundColor: theme.palette.action.hover },
    "& .MuiListItemButton-root.Mui-selected": {
      backgroundColor: theme.palette.action.selected,
      "& .MuiListItemText-primary": {
        fontWeight: 600,
      },
    },
    "& .MuiListItemButton-root.Mui-selected:hover": {
      backgroundColor: theme.palette.action.selected,
    },
  }),
  sideBarPrimaryIcon: (theme) => ({ mr: 1.5, color: theme.palette.text.primary, fontSize: 22 }),
  sideBarIcon: (theme) => ({ mr: 1.5, color: theme.palette.text.primary, fontSize: 22 }),
  sideBarChannelText: { ml: 1.1 },
  sideBarChannelPrimary: (theme) => ({ color: theme.palette.text.primary, fontSize: 14 }),
  sideBarTogglePrimary: (theme) => ({ color: theme.palette.text.secondary, fontSize: 13, fontWeight: 500 }),
  sideBarDivider: (theme) => ({ my: 0.9, mx: 1, borderColor: theme.palette.divider }),
  sideBarSectionTitle: (theme) => ({
    px: 2,
    py: 0.7,
    color: theme.palette.text.secondary,
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: "0.01em",
  }),
  sideBarChannelAvatar: {
    width: 26,
    height: 26,
    fontSize: 12,
    flexShrink: 0,
  },
  userAvatar: (size) => ({
    width: size,
    height: size,
    fontSize: Math.round(size * 0.42),
    lineHeight: 1,
    color: "common.white",
    bgcolor: "grey.500",
  }),
};
