export const formSx = {
  authModal: (theme) => ({
    color: theme.palette.text.secondary,
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: 400,
    bgcolor: theme.palette.background.paper,
    p: 2.5,
    borderRadius: 2,
    textAlign: "center",
  }),
  authCloseButton: (theme) => ({ color: theme.palette.text.secondary }),
  authForm: { display: "flex", flexDirection: "column", gap: 2 },
  authInput: (theme) => ({
    color: theme.palette.text.primary,
    caretColor: theme.palette.text.primary,
    "&:before": { borderBottom: `1px solid ${theme.palette.divider}` },
    "&:hover:not(.Mui-disabled):before": { borderBottom: `1px solid ${theme.palette.text.secondary}` },
    "&.Mui-focused:after": { borderBottom: `2px solid ${theme.palette.text.primary}` },
  }),
  authPrimaryButton: (theme) => ({
    bgcolor: theme.palette.text.primary,
    color: theme.palette.background.default,
    "&:hover": { bgcolor: theme.palette.text.secondary },
    "&.Mui-disabled": {
      bgcolor: theme.palette.action.disabledBackground,
      color: theme.palette.action.disabled,
    },
  }),
  authSecondaryButton: (theme) => ({
    bgcolor: theme.palette.divider,
    color: theme.palette.text.secondary,
    "&:hover": {
      bgcolor: theme.palette.text.primary,
      color: theme.palette.background.default,
    },
  }),
  uploadModal: (theme) => ({
    overflow: "auto",
    color: theme.palette.text.secondary,
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: { xs: "90%", md: 900 },
    height: { xs: "70vh", md: "80vh" },
    bgcolor: theme.palette.background.paper,
    p: 2,
    borderRadius: 2,
  }),
  uploadHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    mb: 2,
  },
  uploadCloseButton: { color: "text.secondary" },
  setDetailsColumns: { direction: "row", spacing: 3 },
  setDetailsLeft: { flex: 2 },
  setDetailsRight: { flex: 1 },
  setDetailsHelper: (invalid) => ({
    mb: 2,
    "& .MuiFormHelperText-root": {
      color: invalid ? "error.main" : "text.secondary",
    },
  }),
  setDetailsDescription: (invalid) => ({
    mb: 3,
    "& .MuiFormHelperText-root": {
      color: invalid ? "error.main" : "text.secondary",
    },
  }),
  setDetailsSectionTitle: { mb: 1 },
  setDetailsPreviewRow: { display: "flex", flexDirection: "row" },
  setDetailsPreviewCard: (aspectRatio, withMargin = false) => ({
    width: 240,
    aspectRatio,
    bgcolor: "background.default",
    border: "1px dashed",
    borderColor: "divider",
    borderRadius: 2,
    cursor: "pointer",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    mr: withMargin ? "10px" : 0,
  }),
  setDetailsUploadHint: { color: "text.secondary" },
  setDetailsPreviewContain: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
    display: "block",
  },
  setDetailsPreviewCover: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  setDetailsTagsTitle: { mt: 3, mb: 1 },
  setDetailsTagField: (invalid) => ({
    mb: 1,
    "& .MuiFormHelperText-root": {
      color: invalid ? "error.main" : "text.secondary",
    },
  }),
  setDetailsPlayerPaper: (aspectRatio) => ({
    borderRadius: 2,
    overflow: "hidden",
    bgcolor: "#000",
    position: "relative",
    aspectRatio,
    width: "100%",
  }),
  setDetailsPlayer: { display: "block", width: "100%", height: "100%" },
  setDetailsActions: { mt: 4 },
  setDetailsPublishButton: (theme) => ({
    borderRadius: "50px",
    textTransform: "none",
    backgroundColor: theme.palette.text.primary,
    color: theme.palette.background.default,
    "&:hover": { backgroundColor: theme.palette.text.secondary },
    "&.Mui-disabled": {
      color: `${theme.palette.action.disabled} !important`,
      opacity: 0.6,
    },
  }),
};
