export const formSx = {
  authModal: (theme) => ({
    color: theme.palette.text.secondary,
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: { xs: "92vw", sm: 400 },
    maxWidth: 420,
    maxHeight: { xs: "88vh", sm: "none" },
    overflowY: { xs: "auto", sm: "visible" },
    bgcolor: theme.palette.background.paper,
    p: 2.5,
    borderRadius: 2,
    textAlign: "center",
  }),
  authCloseButton: (theme) => ({ color: theme.palette.text.secondary }),
  authForm: { display: "flex", flexDirection: "column", gap: 2 },
  authInput: (theme) => ({
    color: theme.palette.text.primary,
    caretColor: theme.palette.text.primary,
    "&:before": { borderBottom: `1px solid ${theme.palette.divider}` },
    "&:hover:not(.Mui-disabled):before": { borderBottom: `1px solid ${theme.palette.text.secondary}` },
    "&.Mui-focused:after": { borderBottom: `2px solid ${theme.palette.text.primary}` },
  }),
  authPrimaryButton: (theme) => ({
    bgcolor: theme.palette.text.primary,
    color: theme.palette.background.default,
    "&:hover": { bgcolor: theme.palette.text.secondary },
    "&.Mui-disabled": {
      bgcolor: theme.palette.action.disabledBackground,
      color: theme.palette.action.disabled,
    },
  }),
  authSecondaryButton: (theme) => ({
    bgcolor: theme.palette.divider,
    color: theme.palette.text.secondary,
    "&:hover": {
      bgcolor: theme.palette.text.primary,
      color: theme.palette.background.default,
    },
  }),
  uploadModal: (theme) => ({
    overflow: "auto",
    color: theme.palette.text.secondary,
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: { xs: "94vw", md: 900 },
    maxWidth: 980,
    height: { xs: "88vh", md: "80vh" },
    bgcolor: theme.palette.background.paper,
    p: 2,
    borderRadius: 2,
  }),
  uploadHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    mb: 2,
  },
  uploadCloseButton: { color: "text.secondary" },
  setDetailsColumns: { direction: { xs: "column", md: "row" }, spacing: { xs: 2, md: 3 } },
  setDetailsLeft: { flex: 2, width: "100%" },
  setDetailsRight: { flex: 1, width: "100%" },
  setDetailsHelper: (invalid) => ({
    mb: 2,
    "& .MuiFormHelperText-root": {
      color: invalid ? "error.main" : "text.secondary",
    },
  }),
  setDetailsDescription: (invalid) => ({
    mb: 3,
    "& .MuiFormHelperText-root": {
      color: invalid ? "error.main" : "text.secondary",
    },
  }),
  setDetailsSectionTitle: { mb: 1 },
  setDetailsPreviewRow: { display: "flex", flexDirection: { xs: "column", sm: "row" }, gap: 1.25 },
  setDetailsPreviewCard: (aspectRatio, withMargin = false) => ({
    width: { xs: "100%", sm: 240 },
    maxWidth: 300,
    aspectRatio,
    bgcolor: "background.default",
    border: "1px dashed",
    borderColor: "divider",
    borderRadius: 2,
    cursor: "pointer",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    mr: withMargin ? { xs: 0, sm: "10px" } : 0,
  }),
  setDetailsUploadHint: { color: "text.secondary" },
  setDetailsPreviewContain: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
    display: "block",
  },
  setDetailsPreviewCover: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  setDetailsTagsTitle: { mt: 3, mb: 1 },
  setDetailsTagField: (invalid) => ({
    mb: 1,
    "& .MuiFormHelperText-root": {
      color: invalid ? "error.main" : "text.secondary",
    },
  }),
  setDetailsPlayerPaper: (aspectRatio) => ({
    borderRadius: 2,
    overflow: "hidden",
    bgcolor: "#000",
    position: "relative",
    aspectRatio,
    width: "100%",
  }),
  setDetailsPlayer: { display: "block", width: "100%", height: "100%" },
  setDetailsActions: { mt: 3, justifyContent: { xs: "stretch", sm: "flex-end" } },
  setDetailsPublishButton: (theme) => ({
    borderRadius: "50px",
    width: { xs: "100%", sm: "auto" },
    textTransform: "none",
    backgroundColor: theme.palette.text.primary,
    color: theme.palette.background.default,
    "&:hover": { backgroundColor: theme.palette.text.secondary },
    "&.Mui-disabled": {
      color: `${theme.palette.action.disabled} !important`,
      opacity: 0.6,
    },
  }),
  selectVideoDropPaper: (theme) => ({
    p: { xs: 2, sm: 4 },
    textAlign: "center",
    cursor: "pointer",
    minHeight: { xs: 140, sm: 200 },
    boxShadow: "none",
    color: theme.palette.text.primary,
    border: "1px dashed",
    borderColor: "divider",
    borderRadius: 2,
    transition: "border-color 0.2s ease, background-color 0.2s ease",
    "&:hover": {
      borderColor: "text.secondary",
      bgcolor: "action.hover",
    },
  }),
  selectVideoUploadIconButton: (theme) => ({
    m: { xs: "24px auto", sm: "48px auto" },
    width: { xs: 96, sm: 136 },
    height: { xs: 96, sm: 136 },
    borderRadius: "50%",
    p: 0,
    border: `2px solid ${theme.palette.divider}`,
    bgcolor: theme.palette.background.default,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "border-color 0.2s ease, background-color 0.2s ease",
    "&:hover": {
      borderColor: theme.palette.text.secondary,
      bgcolor: theme.palette.action.hover,
    },
  }),
  selectVideoUploadIcon: (theme) => ({
    color: theme.palette.text.secondary,
    fontSize: { xs: 52, sm: 72 },
  }),
  selectVideoHint: {
    mt: { xs: 1, sm: 2 },
    color: "text.secondary",
  },
  selectVideoActionButton: {
    display: "block",
    mt: { xs: 1.5, sm: 2 },
    mx: "auto",
    width: { xs: "100%", sm: "auto" },
  },
};
