export const pageSx = {
  watchContainer: {
    maxWidth: 1500,
    mt: 2,
    ml: { xs: 0, md: 4 },
  },
  channelContainer: {
    px: { xs: 2, md: 3 },
    pb: 3,
    mt: 2,
  },
  channelSortRow: {
    display: "flex",
    flexDirection: "row",
    p: 1,
    flexWrap: "wrap",
    gap: 1,
  },
  channelContent: { flex: 1, width: "100%" },
  channelSortButton: {
    borderRadius: 6,
    mr: 0,
  },
  mutedMessage: {
    color: (theme) => theme.palette.text.secondary,
    px: 3,
    py: 2,
  },
  gridSection: { p: 2 },
  searchContainer: { p: 2 },
  searchTitle: { mb: 1 },
  searchMuted: { color: "text.secondary" },
  studioRoot: { p: { xs: 2, md: 3 }, maxWidth: 1200, mx: "auto" },
  studioHeader: { fontWeight: 600, mb: 2 },
  studioMetricsGrid: { mb: 4 },
  studioCard: (theme) => ({ p: 2, bgcolor: theme.palette.background.paper, borderRadius: 3, border: `1px solid ${theme.palette.divider}` }),
  studioCardLabel: (theme) => ({ color: theme.palette.text.secondary, fontSize: 13 }),
  studioBestVideoCard: {
    p: 2,
    bgcolor: "background.paper",
    borderRadius: 3,
    border: "1px solid",
    borderColor: "divider",
    display: "block",
    textDecoration: "none",
    color: "inherit",
    "&:visited": { color: "inherit" },
    "&:hover": { bgcolor: "action.hover" },
  },
  studioBestVideoTitle: { mb: 1, color: "text.secondary", fontSize: 13 },
  studioBestVideoRow: { display: "flex", flexDirection: "row" },
  studioBestVideoImage: { width: "15%", height: "15%", borderRadius: 3 },
  studioBestVideoName: { ml: 2, display: "flex", alignItems: "center" },
  studioVideosTitle: { fontWeight: 600, mb: 1 },
  studioTableContainer: { bgcolor: "background.paper", borderRadius: 3, border: "1px solid", borderColor: "divider" },
  studioTable: { minWidth: 650 },
  studioTableHeadRow: {
    "& th": {
      color: "text.secondary",
      borderColor: "divider",
      fontWeight: 600,
    },
  },
  studioTableRow: {
    "& td": {
      borderColor: "divider",
    },
    "&:hover": {
      bgcolor: "action.hover",
    },
    height: "100px",
  },
  studioVideoCell: { display: "flex" },
  studioVideoImage: { width: "35%", height: "35%", borderRadius: 3 },
  studioVideoName: { display: "flex", alignItems: "center", ml: 2 },
};
