export const pageSx = {
  pageContainer: {
    width: "100%",
    maxWidth: 1600,
    mx: "auto",
    px: { xs: 1, sm: 2, md: 3 },
    py: { xs: 1, sm: 1.5 },
  },
  pageSectionTitle: {
    mb: 1.5,
    display: "flex",
    alignItems: "center",
    gap: 1,
    fontSize: { xs: 18, sm: 22 },
    fontWeight: 700,
    lineHeight: 1.25,
    wordBreak: "break-word",
    "&::after": {
      content: '""',
      display: "block",
      height: 1,
      flex: 1,
      minWidth: 24,
      bgcolor: "divider",
      borderRadius: 999,
    },
  },
  pageStateText: {
    color: "text.secondary",
    px: { xs: 0.5, sm: 0 },
    py: 1,
  },
  infiniteLoader: {
    display: "flex",
    justifyContent: "center",
    py: 2,
  },
  watchContainer: {
    maxWidth: 1600,
    width: "100%",
    mt: { xs: 1, sm: 2 },
    mx: "auto",
    px: { xs: 1, sm: 2, md: 3 },
  },
  watchLayout: {
    display: "flex",
    flexDirection: { xs: "column", xl: "row" },
    alignItems: "flex-start",
    gap: { xs: 2, md: 2.5, xl: 3 },
  },
  watchMainColumn: {
    flex: 1,
    width: "100%",
    minWidth: 0,
  },
  watchSidebar: {
    width: "100%",
    maxWidth: { xs: "100%", sm: 720, md: 920, xl: 360 },
    mx: { xs: "auto", xl: 0 },
    flexShrink: 0,
    p: 0,
    bgcolor: "transparent",
    boxShadow: "none",
    position: { xs: "static", xl: "sticky" },
    top: { xl: 80 },
    alignSelf: { xl: "flex-start" },
  },
  watchSidebarSection: {
    borderRadius: 2,
  },
  watchSidebarTitle: {
    mb: 1.25,
    px: 0.5,
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: "text.secondary",
  },
  watchSidebarLoader: {
    py: 1,
    display: "flex",
    justifyContent: "center",
  },
  watchSidebarItem: {
    display: "flex",
    gap: { xs: 1, sm: 1.25 },
    textDecoration: "none",
    color: "text.primary",
    borderRadius: 2,
    alignItems: "flex-start",
    p: { xs: 0.4, sm: 0.5 },
    border: "1px solid transparent",
    transition: "background-color 160ms ease, border-color 160ms ease",
    "&:hover": { bgcolor: "action.hover", borderColor: "divider" },
  },
  watchSidebarThumb: {
    width: { xs: 148, sm: 176, md: 208, xl: 168 },
    minWidth: { xs: 132, sm: 162, md: 188, xl: 168 },
    maxWidth: "48%",
    aspectRatio: "16 / 9",
    objectFit: "cover",
    borderRadius: 1.25,
    flexShrink: 0,
    bgcolor: "action.hover",
  },
  watchSidebarMeta: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 0.2,
  },
  watchSidebarMetaTitle: {
    fontSize: { xs: 13, sm: 13.5 },
    fontWeight: 600,
    lineHeight: 1.3,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  watchSidebarMetaSecondary: {
    fontSize: 12,
    color: "text.secondary",
    lineHeight: 1.25,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  channelContainer: {
    px: { xs: 2, md: 3 },
    pb: 3,
    mt: { xs: 1, sm: 2 },
    maxWidth: 1600,
    mx: "auto",
  },
  channelSortRow: {
    display: "flex",
    flexDirection: { xs: "row", sm: "row" },
    p: { xs: 0.5, sm: 1 },
    flexWrap: "wrap",
    gap: 1,
    alignItems: "center",
  },
  channelContent: { flex: 1, width: "100%" },
  channelSortButton: {
    borderRadius: 6,
    mr: 0,
    px: { xs: 1.5, sm: 2 },
    minHeight: { xs: 34, sm: 36 },
  },
  mutedMessage: {
    color: (theme) => theme.palette.text.secondary,
    px: 3,
    py: 2,
  },
  gridSection: { p: { xs: 1, sm: 2 } },
  searchContainer: {
    p: { xs: 1, sm: 2 },
    maxWidth: 1600,
    mx: "auto",
  },
  searchTitle: { mb: 1, lineHeight: 1.3, wordBreak: "break-word" },
  searchMuted: { color: "text.secondary" },
  searchSectionTitle: {
    mb: 1,
    mt: 1,
    fontWeight: 600,
  },
  searchResultBlock: {
    mb: 2.5,
  },
  searchChannelList: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
  },
  searchChannelItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: { xs: 0.75, sm: 1.5 },
    borderRadius: 0,
    borderBottom: "1px solid",
    borderBottomColor: "divider",
    transition: "background-color 0.2s ease",
    "&:hover": {
      bgcolor: "action.hover",
    },
    "&:first-of-type": {
      borderTop: "1px solid",
      borderTopColor: "divider",
    },
  },
  searchChannelMainLink: {
    display: "flex",
    alignItems: "center",
    gap: { xs: 1, sm: 1.5 },
    px: { xs: 0.5, sm: 0.75 },
    py: { xs: 1, sm: 1.25 },
    textDecoration: "none",
    color: "text.primary",
    minWidth: 0,
    flex: 1,
  },
  searchChannelAvatarWrap: {
    flexShrink: 0,
  },
  searchChannelTextWrap: {
    minWidth: 0,
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 0.35,
  },
  searchChannelName: {
    fontWeight: 700,
    fontSize: { xs: 16, sm: 19 },
    lineHeight: 1.25,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  searchChannelMeta: {
    fontSize: { xs: 12, sm: 14 },
    color: "text.secondary",
    lineHeight: 1.3,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  searchChannelAction: {
    pr: { xs: 0.5, sm: 0.75 },
    flexShrink: 0,
    display: "block",
  },
  searchVideoList: {
    display: "flex",
    flexDirection: "column",
    gap: { xs: 1.25, sm: 1.5 },
  },
  searchVideoItem: {
    display: "flex",
    flexDirection: { xs: "column", sm: "row" },
    gap: { xs: 1, sm: 1.5 },
    textDecoration: "none",
    color: "text.primary",
    borderRadius: 2,
    p: { xs: 0.5, sm: 0.75 },
    border: "1px solid transparent",
    transition: "background-color 0.2s ease, border-color 0.2s ease",
    "&:hover": {
      bgcolor: "action.hover",
      borderColor: "divider",
    },
  },
  searchVideoThumbWrap: {
    width: { xs: "100%", sm: 320, md: 360 },
    minWidth: { sm: 300, md: 340 },
    maxWidth: { xs: "100%", sm: 360 },
    aspectRatio: "16 / 9",
    overflow: "hidden",
    borderRadius: 1.5,
    bgcolor: "action.hover",
    flexShrink: 0,
  },
  searchVideoThumb: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  searchVideoMeta: {
    minWidth: 0,
    flex: 1,
    pt: { sm: 0.25 },
  },
  searchVideoTitle: {
    fontSize: { xs: 16, sm: 18 },
    fontWeight: 600,
    lineHeight: 1.3,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    mb: 0.6,
  },
  searchVideoStats: {
    fontSize: 13,
    color: "text.secondary",
    mb: 0.9,
  },
  searchVideoChannelRow: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    mb: 0.8,
  },
  searchVideoChannel: {
    fontSize: 13,
    fontWeight: 500,
    color: "text.secondary",
    minWidth: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  searchVideoDescription: {
    fontSize: 13,
    color: "text.secondary",
    lineHeight: 1.35,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    wordBreak: "break-word",
  },
  studioRoot: { p: { xs: 1, sm: 2, md: 3 }, maxWidth: 1400, mx: "auto" },
  studioHeader: { fontWeight: 600, mb: 2 },
  studioMetricsGrid: { mb: 4 },
  studioCard: (theme) => ({
    p: 2,
    bgcolor: theme.palette.background.paper,
    borderRadius: 3,
    border: `1px solid ${theme.palette.divider}`,
    boxShadow: theme.palette.mode === "light" ? "0 8px 22px rgba(15,23,42,0.05)" : "none",
  }),
  studioCardLabel: (theme) => ({ color: theme.palette.text.secondary, fontSize: 13 }),
  studioBestVideoCard: {
    p: 2,
    bgcolor: "background.paper",
    borderRadius: 3,
    border: "1px solid",
    borderColor: "divider",
    display: "block",
    textDecoration: "none",
    color: "inherit",
    "&:visited": { color: "inherit" },
    transition: "background-color 0.2s ease, border-color 0.2s ease",
    "&:hover": { bgcolor: "action.hover", borderColor: "text.secondary" },
  },
  studioBestVideoTitle: { mb: 1, color: "text.secondary", fontSize: 13 },
  studioBestVideoRow: { display: "flex", flexDirection: "row", alignItems: "center", gap: 1.5 },
  studioBestVideoImage: { width: { xs: 72, sm: 84 }, height: { xs: 40, sm: 48 }, borderRadius: 1.5, objectFit: "cover" },
  studioBestVideoName: { display: "flex", alignItems: "center", minWidth: 0, flex: 1 },
  studioVideosTitle: { fontWeight: 600, mb: 1 },
  studioTableContainer: { bgcolor: "background.paper", borderRadius: 3, border: "1px solid", borderColor: "divider", overflowX: "auto" },
  studioTable: { minWidth: { xs: 700, sm: 940 }, width: "100%", tableLayout: "fixed" },
  studioTableHeadRow: {
    "& th": {
      color: "text.secondary",
      borderColor: "divider",
      fontWeight: 600,
      py: 1.25,
      px: 1,
      whiteSpace: "nowrap",
    },
    "& th:nth-of-type(1)": { width: "34%" },
    "& th:nth-of-type(2)": { width: "14%" },
    "& th:nth-of-type(3)": { width: "10%" },
    "& th:nth-of-type(4)": { width: "10%" },
    "& th:nth-of-type(5)": { width: "14%" },
    "& th:nth-of-type(6)": { width: "12%" },
    "& th:nth-of-type(7)": { width: "6%" },
  },
  studioTableRow: {
    "& td": {
      borderColor: "divider",
      py: 1,
      px: 1,
      verticalAlign: "middle",
    },
    "&:hover": {
      bgcolor: "action.hover",
    },
    height: { xs: 84, sm: 100 },
  },
  studioVideoCell: { minWidth: 0, cursor: "pointer" },
  studioVideoCellContent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    minWidth: 0,
    width: "100%",
    gap: { xs: 1, sm: 1.5 },
  },
  studioVideoImage: { width: { xs: 72, sm: 88 }, height: { xs: 40, sm: 50 }, borderRadius: 1.5, objectFit: "cover", flexShrink: 0 },
  studioVideoName: {
    display: "-webkit-box",
    minWidth: 0,
    overflow: "hidden",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    textAlign: "left",
    lineHeight: 1.3,
    wordBreak: "break-word",
  },
  studioMobileList: { mt: 1, gap: 1 },
  studioMobileCard: {
    p: 1.25,
    display: "flex",
    gap: 1.25,
    borderRadius: 2,
    border: "1px solid",
    borderColor: "divider",
    bgcolor: "background.paper",
    cursor: "pointer",
  },
  studioMobileThumb: { width: 120, height: 68, borderRadius: 1.5, objectFit: "cover", flexShrink: 0 },
  studioMobileMeta: { minWidth: 0, flex: 1, display: "flex", flexDirection: "column", gap: 0.25 },
  studioStatusCell: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    maxWidth: "100%",
  },
  studioStatusLabel: {
    fontSize: 12,
    lineHeight: 1.2,
    color: "text.secondary",
    whiteSpace: "nowrap",
  },
  studioStatusErrorIcon: { color: "error.main", fontSize: 17 },
  studioStatusDoneIcon: { color: "success.main", fontSize: 17 },
  studioStatusProcessingIcon: {
    color: "warning.main",
    fontSize: 17,
    animation: "studioStatusSpin 1.2s linear infinite",
    "@keyframes studioStatusSpin": {
      from: { transform: "rotate(0deg)" },
      to: { transform: "rotate(360deg)" },
    },
  },
  studioDeleteIcon: {
    color: "error.main",
    "&.Mui-disabled": { color: "action.disabled" },
  },
};
