export const pageSx = {
  watchContainer: {
    maxWidth: 1500,
    width: "100%",
    mt: 2,
    mx: "auto",
    px: { xs: 0.5, sm: 1 },
    ml: { xs: 0, md: 4 },
  },
  watchLayout: {
    display: "flex",
    flexDirection: { xs: "column", lg: "row" },
    alignItems: "flex-start",
    gap: { xs: 2, lg: 3 },
  },
  watchMainColumn: {
    flex: 1,
    minWidth: 0,
  },
  watchSidebar: {
    width: { xs: "100%", lg: 360 },
    flexShrink: 0,
    position: { xs: "static", lg: "sticky" },
    top: { lg: 80 },
    alignSelf: { lg: "flex-start" },
  },
  watchSidebarTitle: {
    mb: 1,
  },
  watchSidebarLoader: {
    py: 1,
    display: "flex",
    justifyContent: "center",
  },
  watchSidebarItem: {
    display: "flex",
    gap: 1,
    textDecoration: "none",
    color: "text.primary",
    borderRadius: 2,
    p: 0.5,
    "&:hover": { bgcolor: "action.hover" },
  },
  watchSidebarThumb: {
    width: 160,
    aspectRatio: "16 / 9",
    objectFit: "cover",
    borderRadius: 1.5,
    flexShrink: 0,
    bgcolor: "action.hover",
  },
  watchSidebarMeta: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 0.25,
  },
  channelContainer: {
    px: { xs: 2, md: 3 },
    pb: 3,
    mt: 2,
  },
  channelSortRow: {
    display: "flex",
    flexDirection: "row",
    p: 1,
    flexWrap: "wrap",
    gap: 1,
  },
  channelContent: { flex: 1, width: "100%" },
  channelSortButton: {
    borderRadius: 6,
    mr: 0,
  },
  mutedMessage: {
    color: (theme) => theme.palette.text.secondary,
    px: 3,
    py: 2,
  },
  gridSection: { p: { xs: 1, sm: 2 } },
  searchContainer: { p: { xs: 1, sm: 2 } },
  searchTitle: { mb: 1 },
  searchMuted: { color: "text.secondary" },
  studioRoot: { p: { xs: 2, md: 3 }, maxWidth: 1200, mx: "auto" },
  studioHeader: { fontWeight: 600, mb: 2 },
  studioMetricsGrid: { mb: 4 },
  studioCard: (theme) => ({ p: 2, bgcolor: theme.palette.background.paper, borderRadius: 3, border: `1px solid ${theme.palette.divider}` }),
  studioCardLabel: (theme) => ({ color: theme.palette.text.secondary, fontSize: 13 }),
  studioBestVideoCard: {
    p: 2,
    bgcolor: "background.paper",
    borderRadius: 3,
    border: "1px solid",
    borderColor: "divider",
    display: "block",
    textDecoration: "none",
    color: "inherit",
    "&:visited": { color: "inherit" },
    "&:hover": { bgcolor: "action.hover" },
  },
  studioBestVideoTitle: { mb: 1, color: "text.secondary", fontSize: 13 },
  studioBestVideoRow: { display: "flex", flexDirection: "row", alignItems: "center", gap: 1.5 },
  studioBestVideoImage: { width: { xs: 72, sm: 84 }, height: { xs: 40, sm: 48 }, borderRadius: 1.5, objectFit: "cover" },
  studioBestVideoName: { display: "flex", alignItems: "center", minWidth: 0, flex: 1 },
  studioVideosTitle: { fontWeight: 600, mb: 1 },
  studioTableContainer: { bgcolor: "background.paper", borderRadius: 3, border: "1px solid", borderColor: "divider", overflowX: "auto" },
  studioTable: { minWidth: { xs: 520, sm: 650 } },
  studioTableHeadRow: {
    "& th": {
      color: "text.secondary",
      borderColor: "divider",
      fontWeight: 600,
    },
  },
  studioTableRow: {
    "& td": {
      borderColor: "divider",
    },
    "&:hover": {
      bgcolor: "action.hover",
    },
    height: "100px",
  },
  studioVideoCell: { display: "flex", alignItems: "center", minWidth: 220, gap: 1.5 },
  studioVideoImage: { width: { xs: 72, sm: 88 }, height: { xs: 40, sm: 50 }, borderRadius: 1.5, objectFit: "cover", flexShrink: 0 },
  studioVideoName: { display: "flex", alignItems: "center", minWidth: 0, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
};
