export const skeletonSx = {
  videoGrid: {
    display: "grid",
    gridTemplateColumns: {
      xs: "repeat(1, 1fr)",
      sm: "repeat(auto-fill, minmax(280px, 1fr))",
    },
    gap: 2.5,
    p: 2,
    justifyItems: "center",
    width: "100%",
  },
  videoCard: { width: "100%", minWidth: { xs: 0, sm: 280 }, maxWidth: 320 },
  videoPreviewWrap: {
    position: "relative",
    width: "100%",
    pt: "56.25%",
    borderRadius: 2,
    overflow: "hidden",
  },
  videoPreview: { position: "absolute", inset: 0, width: "100%", height: "100%" },
  videoMetaRow: { mt: 1.5, display: "flex", gap: 1.5 },
  channelSidebarCard: (theme) => ({
    p: 2,
    width: { xs: "100%", md: 280 },
    bgcolor: "transparent",
    boxShadow: "none",
    border: `1px solid ${theme.palette.divider}`,
    borderRadius: 3,
    display: "flex",
    flexDirection: "column",
    gap: 1.5,
    position: { md: "sticky" },
    top: 80,
  }),
  channelSortButton: { borderRadius: 3 },
  channelSidebarRect: { p: 2, width: { xs: "100%", md: 280 }, height: 300, borderRadius: 3 },
  channelSortRowItem: { width: 120, height: 36, borderRadius: 3 },
  studioCard: (theme) => ({
    p: 2,
    bgcolor: theme.palette.background.paper,
    borderRadius: 3,
    border: `1px solid ${theme.palette.divider}`,
  }),
  studioTableCell: { py: 1.8 },
  studioTitle: { mb: 3 },
  studioSectionTitle: { mt: 5, mb: 2 },
  studioThumb: { borderRadius: 1 },
  watchPlayerWrap: {
    width: "100%",
    maxWidth: 1200,
    borderRadius: 2,
    overflow: "hidden",
  },
  watchPlayer: { width: "100%", aspectRatio: "16 / 9" },
  watchInfo: { maxWidth: 1200, width: "100%", mt: 2, px: 1 },
  watchTitle: { mb: 1.2 },
  watchMetaRow: { display: "flex", alignItems: "center", gap: 1.5 },
  watchDescription: { mt: 2, borderRadius: 2 },
  watchRoot: { maxWidth: 1300, mt: 2, ml: { xs: 0, md: 4 } },
  watchFrame: { width: "100%", maxWidth: 1300, mx: "auto", aspectRatio: "16 / 9" },
  watchPlayerRect: { width: "100%", height: "100%", borderRadius: 2 },
  watchChannelRow: { display: "flex", alignItems: "center", gap: 2 },
  watchGrow: { flexGrow: 1 },
  watchButton: { width: "10%", height: 50, borderRadius: 5 },
  watchTextButton: { width: "10%", height: 50 },
  watchCommentTitle: { width: "20%", height: 20 },
  watchDescriptionBlock: { width: "100%", height: 150, borderRadius: 2 },
};
