export const skeletonSx = {
  videoGrid: {
    display: "grid",
    gridTemplateColumns: {
      xs: "1fr",
      sm: "repeat(2, minmax(0, 1fr))",
      md: "repeat(auto-fill, minmax(260px, 1fr))",
      xl: "repeat(auto-fill, minmax(280px, 1fr))",
    },
    gap: { xs: 1.5, sm: 2, md: 2.5 },
    p: { xs: 0.5, sm: 1, md: 2 },
    justifyItems: "center",
    width: "100%",
  },
  videoCard: { width: "100%", minWidth: 0, maxWidth: { xs: "100%", md: 360, xl: 320 } },
  videoPreviewWrap: {
    position: "relative",
    width: "100%",
    pt: "56.25%",
    borderRadius: 2,
    overflow: "hidden",
  },
  videoPreview: { position: "absolute", inset: 0, width: "100%", height: "100%" },
  videoMetaRow: { mt: 1.5, display: "flex", gap: 1.5 },
  channelSidebarCard: (theme) => ({
    p: 2,
    width: { xs: "100%", lg: 280 },
    bgcolor: "transparent",
    boxShadow: "none",
    border: `1px solid ${theme.palette.divider}`,
    borderRadius: 3,
    display: "flex",
    flexDirection: "column",
    gap: 1.5,
    position: { lg: "sticky" },
    top: 80,
  }),
  channelSortButton: { borderRadius: 3 },
  channelSidebarRect: { p: 2, width: { xs: "100%", lg: 280 }, height: { xs: 220, sm: 260, lg: 300 }, borderRadius: 3 },
  channelSortRowItem: { width: { xs: 96, sm: 120 }, height: 36, borderRadius: 3 },
  studioCard: (theme) => ({
    p: 2,
    bgcolor: theme.palette.background.paper,
    borderRadius: 3,
    border: `1px solid ${theme.palette.divider}`,
  }),
  studioTableCell: { py: 1.8 },
  studioTitle: { mb: 3 },
  studioSectionTitle: { mt: 5, mb: 2 },
  studioThumb: { borderRadius: 1 },
  watchPlayerWrap: {
    width: "100%",
    maxWidth: 1200,
    borderRadius: 2,
    overflow: "hidden",
  },
  watchPlayer: { width: "100%", aspectRatio: "16 / 9" },
  watchInfo: { maxWidth: 1200, width: "100%", mt: 2, px: 1 },
  watchTitle: { mb: 1.2 },
  watchMetaRow: { display: "flex", alignItems: "center", gap: 1.5 },
  watchDescription: { mt: 2, borderRadius: 2 },
  watchRoot: { maxWidth: 1600, mt: { xs: 1, sm: 2 }, mx: "auto", px: { xs: 1, sm: 2, md: 3 } },
  watchFrame: { width: "100%", maxWidth: 1300, mx: "auto", aspectRatio: "16 / 9" },
  watchPlayerRect: { width: "100%", height: "100%", borderRadius: 2 },
  watchChannelRow: { display: "flex", alignItems: "center", gap: { xs: 1, sm: 2 }, flexWrap: "wrap" },
  watchGrow: { flexGrow: 1 },
  watchButton: { width: { xs: 96, sm: 140 }, height: 40, borderRadius: 5 },
  watchTextButton: { width: { xs: 110, sm: 160 }, height: 28 },
  watchCommentTitle: { width: { xs: 140, sm: 220 }, height: 20 },
  watchDescriptionBlock: { width: "100%", height: 150, borderRadius: 2 },
};
